[package]
name = "hyper_auth"
version = "0.1.0"
authors = ["radekg <radek@gruchalski.com>"]

[dependencies]
hyper = "0.5.1"
log = "0.3.1"
rust-crypto = "0.2.31"
url = "0.2.34"
uuid = "0.1.17"
rustc-serialize = "0.3"